input_data_path: 'data/raw/heart.csv'
output_model_path: 'models/model_LR.pkl'
metric_path: 'models/metrics_LR.json'
transformer_path: 'models/transformer_LR.pkl'
splitting_params:
  val_size: 0.1
  random_state: 3
train_params:
  model_type: 'LogisticRegression'
feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
    - 'ca'
  target_col: 'target'